name: Dependabot Automerge PR
on:
  pull_request:
    branches:
      - master
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    env:
      GITHUB_TOKEN: ${{ github.token }}
      MERGE_LABELS: dependencies
      MERGE_COMMIT_MESSAGE: "ðŸ”€ Automerge pull request #${{ github.event.pull_request.number }}"
    name: Dependabot Automerge
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Wait for status checks
        uses: WyriHaximus/github-action-wait-for-status@v1.0.0
        with:
          ignoreActions: automerge
      - name: Automerge
        uses: pascalgn/automerge-action@v0.8.5
        if: steps.waitforstatuschecks.outputs.status == 'success'
